/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWallpapersRouteImport } from './routes/_authenticated.wallpapers'
import { Route as AuthenticatedVisualizationsRouteImport } from './routes/_authenticated.visualizations'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated.tools'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedWallpapersIndexRouteImport } from './routes/_authenticated.wallpapers.index'
import { Route as ApiAiGenerateRoomRouteImport } from './routes/api.ai.generate-room'
import { Route as ApiAiDetectWallRouteImport } from './routes/api.ai.detect-wall'
import { Route as ApiAiApplyWallpaperToUploadedRoomRouteImport } from './routes/api.ai.apply-wallpaper-to-uploaded-room'
import { Route as ApiAiApplyWallpaperRouteImport } from './routes/api.ai.apply-wallpaper'
import { Route as AuthenticatedWallpapersNewRouteImport } from './routes/_authenticated.wallpapers.new'
import { Route as AuthenticatedWallpapersIdRouteImport } from './routes/_authenticated.wallpapers.$id'
import { Route as AuthenticatedToolsWallpaperVisualizerRouteImport } from './routes/_authenticated.tools.wallpaper-visualizer'
import { Route as AuthenticatedToolsImageCropRouteImport } from './routes/_authenticated.tools.image-crop'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWallpapersRoute = AuthenticatedWallpapersRouteImport.update({
  id: '/wallpapers',
  path: '/wallpapers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVisualizationsRoute =
  AuthenticatedVisualizationsRouteImport.update({
    id: '/visualizations',
    path: '/visualizations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWallpapersIndexRoute =
  AuthenticatedWallpapersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWallpapersRoute,
  } as any)
const ApiAiGenerateRoomRoute = ApiAiGenerateRoomRouteImport.update({
  id: '/api/ai/generate-room',
  path: '/api/ai/generate-room',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiDetectWallRoute = ApiAiDetectWallRouteImport.update({
  id: '/api/ai/detect-wall',
  path: '/api/ai/detect-wall',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiApplyWallpaperToUploadedRoomRoute =
  ApiAiApplyWallpaperToUploadedRoomRouteImport.update({
    id: '/api/ai/apply-wallpaper-to-uploaded-room',
    path: '/api/ai/apply-wallpaper-to-uploaded-room',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiApplyWallpaperRoute = ApiAiApplyWallpaperRouteImport.update({
  id: '/api/ai/apply-wallpaper',
  path: '/api/ai/apply-wallpaper',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWallpapersNewRoute =
  AuthenticatedWallpapersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedWallpapersRoute,
  } as any)
const AuthenticatedWallpapersIdRoute =
  AuthenticatedWallpapersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedWallpapersRoute,
  } as any)
const AuthenticatedToolsWallpaperVisualizerRoute =
  AuthenticatedToolsWallpaperVisualizerRouteImport.update({
    id: '/wallpaper-visualizer',
    path: '/wallpaper-visualizer',
    getParentRoute: () => AuthenticatedToolsRoute,
  } as any)
const AuthenticatedToolsImageCropRoute =
  AuthenticatedToolsImageCropRouteImport.update({
    id: '/image-crop',
    path: '/image-crop',
    getParentRoute: () => AuthenticatedToolsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tools': typeof AuthenticatedToolsRouteWithChildren
  '/visualizations': typeof AuthenticatedVisualizationsRoute
  '/wallpapers': typeof AuthenticatedWallpapersRouteWithChildren
  '/tools/image-crop': typeof AuthenticatedToolsImageCropRoute
  '/tools/wallpaper-visualizer': typeof AuthenticatedToolsWallpaperVisualizerRoute
  '/wallpapers/$id': typeof AuthenticatedWallpapersIdRoute
  '/wallpapers/new': typeof AuthenticatedWallpapersNewRoute
  '/api/ai/apply-wallpaper': typeof ApiAiApplyWallpaperRoute
  '/api/ai/apply-wallpaper-to-uploaded-room': typeof ApiAiApplyWallpaperToUploadedRoomRoute
  '/api/ai/detect-wall': typeof ApiAiDetectWallRoute
  '/api/ai/generate-room': typeof ApiAiGenerateRoomRoute
  '/wallpapers/': typeof AuthenticatedWallpapersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tools': typeof AuthenticatedToolsRouteWithChildren
  '/visualizations': typeof AuthenticatedVisualizationsRoute
  '/tools/image-crop': typeof AuthenticatedToolsImageCropRoute
  '/tools/wallpaper-visualizer': typeof AuthenticatedToolsWallpaperVisualizerRoute
  '/wallpapers/$id': typeof AuthenticatedWallpapersIdRoute
  '/wallpapers/new': typeof AuthenticatedWallpapersNewRoute
  '/api/ai/apply-wallpaper': typeof ApiAiApplyWallpaperRoute
  '/api/ai/apply-wallpaper-to-uploaded-room': typeof ApiAiApplyWallpaperToUploadedRoomRoute
  '/api/ai/detect-wall': typeof ApiAiDetectWallRoute
  '/api/ai/generate-room': typeof ApiAiGenerateRoomRoute
  '/wallpapers': typeof AuthenticatedWallpapersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRouteWithChildren
  '/_authenticated/visualizations': typeof AuthenticatedVisualizationsRoute
  '/_authenticated/wallpapers': typeof AuthenticatedWallpapersRouteWithChildren
  '/_authenticated/tools/image-crop': typeof AuthenticatedToolsImageCropRoute
  '/_authenticated/tools/wallpaper-visualizer': typeof AuthenticatedToolsWallpaperVisualizerRoute
  '/_authenticated/wallpapers/$id': typeof AuthenticatedWallpapersIdRoute
  '/_authenticated/wallpapers/new': typeof AuthenticatedWallpapersNewRoute
  '/api/ai/apply-wallpaper': typeof ApiAiApplyWallpaperRoute
  '/api/ai/apply-wallpaper-to-uploaded-room': typeof ApiAiApplyWallpaperToUploadedRoomRoute
  '/api/ai/detect-wall': typeof ApiAiDetectWallRoute
  '/api/ai/generate-room': typeof ApiAiGenerateRoomRoute
  '/_authenticated/wallpapers/': typeof AuthenticatedWallpapersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/profile'
    | '/tools'
    | '/visualizations'
    | '/wallpapers'
    | '/tools/image-crop'
    | '/tools/wallpaper-visualizer'
    | '/wallpapers/$id'
    | '/wallpapers/new'
    | '/api/ai/apply-wallpaper'
    | '/api/ai/apply-wallpaper-to-uploaded-room'
    | '/api/ai/detect-wall'
    | '/api/ai/generate-room'
    | '/wallpapers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/profile'
    | '/tools'
    | '/visualizations'
    | '/tools/image-crop'
    | '/tools/wallpaper-visualizer'
    | '/wallpapers/$id'
    | '/wallpapers/new'
    | '/api/ai/apply-wallpaper'
    | '/api/ai/apply-wallpaper-to-uploaded-room'
    | '/api/ai/detect-wall'
    | '/api/ai/generate-room'
    | '/wallpapers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/tools'
    | '/_authenticated/visualizations'
    | '/_authenticated/wallpapers'
    | '/_authenticated/tools/image-crop'
    | '/_authenticated/tools/wallpaper-visualizer'
    | '/_authenticated/wallpapers/$id'
    | '/_authenticated/wallpapers/new'
    | '/api/ai/apply-wallpaper'
    | '/api/ai/apply-wallpaper-to-uploaded-room'
    | '/api/ai/detect-wall'
    | '/api/ai/generate-room'
    | '/_authenticated/wallpapers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAiApplyWallpaperRoute: typeof ApiAiApplyWallpaperRoute
  ApiAiApplyWallpaperToUploadedRoomRoute: typeof ApiAiApplyWallpaperToUploadedRoomRoute
  ApiAiDetectWallRoute: typeof ApiAiDetectWallRoute
  ApiAiGenerateRoomRoute: typeof ApiAiGenerateRoomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallpapers': {
      id: '/_authenticated/wallpapers'
      path: '/wallpapers'
      fullPath: '/wallpapers'
      preLoaderRoute: typeof AuthenticatedWallpapersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/visualizations': {
      id: '/_authenticated/visualizations'
      path: '/visualizations'
      fullPath: '/visualizations'
      preLoaderRoute: typeof AuthenticatedVisualizationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/wallpapers/': {
      id: '/_authenticated/wallpapers/'
      path: '/'
      fullPath: '/wallpapers/'
      preLoaderRoute: typeof AuthenticatedWallpapersIndexRouteImport
      parentRoute: typeof AuthenticatedWallpapersRoute
    }
    '/api/ai/generate-room': {
      id: '/api/ai/generate-room'
      path: '/api/ai/generate-room'
      fullPath: '/api/ai/generate-room'
      preLoaderRoute: typeof ApiAiGenerateRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/detect-wall': {
      id: '/api/ai/detect-wall'
      path: '/api/ai/detect-wall'
      fullPath: '/api/ai/detect-wall'
      preLoaderRoute: typeof ApiAiDetectWallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/apply-wallpaper-to-uploaded-room': {
      id: '/api/ai/apply-wallpaper-to-uploaded-room'
      path: '/api/ai/apply-wallpaper-to-uploaded-room'
      fullPath: '/api/ai/apply-wallpaper-to-uploaded-room'
      preLoaderRoute: typeof ApiAiApplyWallpaperToUploadedRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/apply-wallpaper': {
      id: '/api/ai/apply-wallpaper'
      path: '/api/ai/apply-wallpaper'
      fullPath: '/api/ai/apply-wallpaper'
      preLoaderRoute: typeof ApiAiApplyWallpaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallpapers/new': {
      id: '/_authenticated/wallpapers/new'
      path: '/new'
      fullPath: '/wallpapers/new'
      preLoaderRoute: typeof AuthenticatedWallpapersNewRouteImport
      parentRoute: typeof AuthenticatedWallpapersRoute
    }
    '/_authenticated/wallpapers/$id': {
      id: '/_authenticated/wallpapers/$id'
      path: '/$id'
      fullPath: '/wallpapers/$id'
      preLoaderRoute: typeof AuthenticatedWallpapersIdRouteImport
      parentRoute: typeof AuthenticatedWallpapersRoute
    }
    '/_authenticated/tools/wallpaper-visualizer': {
      id: '/_authenticated/tools/wallpaper-visualizer'
      path: '/wallpaper-visualizer'
      fullPath: '/tools/wallpaper-visualizer'
      preLoaderRoute: typeof AuthenticatedToolsWallpaperVisualizerRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/tools/image-crop': {
      id: '/_authenticated/tools/image-crop'
      path: '/image-crop'
      fullPath: '/tools/image-crop'
      preLoaderRoute: typeof AuthenticatedToolsImageCropRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
  }
}

interface AuthenticatedToolsRouteChildren {
  AuthenticatedToolsImageCropRoute: typeof AuthenticatedToolsImageCropRoute
  AuthenticatedToolsWallpaperVisualizerRoute: typeof AuthenticatedToolsWallpaperVisualizerRoute
}

const AuthenticatedToolsRouteChildren: AuthenticatedToolsRouteChildren = {
  AuthenticatedToolsImageCropRoute: AuthenticatedToolsImageCropRoute,
  AuthenticatedToolsWallpaperVisualizerRoute:
    AuthenticatedToolsWallpaperVisualizerRoute,
}

const AuthenticatedToolsRouteWithChildren =
  AuthenticatedToolsRoute._addFileChildren(AuthenticatedToolsRouteChildren)

interface AuthenticatedWallpapersRouteChildren {
  AuthenticatedWallpapersIdRoute: typeof AuthenticatedWallpapersIdRoute
  AuthenticatedWallpapersNewRoute: typeof AuthenticatedWallpapersNewRoute
  AuthenticatedWallpapersIndexRoute: typeof AuthenticatedWallpapersIndexRoute
}

const AuthenticatedWallpapersRouteChildren: AuthenticatedWallpapersRouteChildren =
  {
    AuthenticatedWallpapersIdRoute: AuthenticatedWallpapersIdRoute,
    AuthenticatedWallpapersNewRoute: AuthenticatedWallpapersNewRoute,
    AuthenticatedWallpapersIndexRoute: AuthenticatedWallpapersIndexRoute,
  }

const AuthenticatedWallpapersRouteWithChildren =
  AuthenticatedWallpapersRoute._addFileChildren(
    AuthenticatedWallpapersRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRouteWithChildren
  AuthenticatedVisualizationsRoute: typeof AuthenticatedVisualizationsRoute
  AuthenticatedWallpapersRoute: typeof AuthenticatedWallpapersRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRouteWithChildren,
  AuthenticatedVisualizationsRoute: AuthenticatedVisualizationsRoute,
  AuthenticatedWallpapersRoute: AuthenticatedWallpapersRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAiApplyWallpaperRoute: ApiAiApplyWallpaperRoute,
  ApiAiApplyWallpaperToUploadedRoomRoute:
    ApiAiApplyWallpaperToUploadedRoomRoute,
  ApiAiDetectWallRoute: ApiAiDetectWallRoute,
  ApiAiGenerateRoomRoute: ApiAiGenerateRoomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
